
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package yacc;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SPECIFIER = 3;
  public static final int LT = 20;
  public static final int ELSE = 16;
  public static final int EXCL = 22;
  public static final int SEMI = 2;
  public static final int WHILE = 13;
  public static final int STAR = 8;
  public static final int VARIABLE = 23;
  public static final int SWITCH = 17;
  public static final int IF = 15;
  public static final int COMPARATOR = 24;
  public static final int GT = 21;
  public static final int DO = 14;
  public static final int EQUALS = 7;
  public static final int COMMA = 9;
  public static final int LEFTPARAN = 5;
  public static final int RIGHTPARAN = 6;
  public static final int EOF = 0;
  public static final int BREAK = 18;
  public static final int CASE = 19;
  public static final int error = 1;
  public static final int RETURNTYPE = 4;
  public static final int FOR = 12;
  public static final int LEFTBRACE = 10;
  public static final int RIGHTBRACE = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "SPECIFIER",
  "RETURNTYPE",
  "LEFTPARAN",
  "RIGHTPARAN",
  "EQUALS",
  "STAR",
  "COMMA",
  "LEFTBRACE",
  "RIGHTBRACE",
  "FOR",
  "WHILE",
  "DO",
  "IF",
  "ELSE",
  "SWITCH",
  "BREAK",
  "CASE",
  "LT",
  "GT",
  "EXCL",
  "VARIABLE",
  "COMPARATOR"
  };
}

